[build]
  command = "yarn --cwd ./frontend install && yarn --cwd ./frontend build && make build"
  functions = "backend/functions"
  publish = "frontend/build"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/pubu/smile-feedback-react-lambda"

